### ISSUE TITLE
Wheel building repository

### ISSUE THREAD

**Issue by matthew-brett** [luispedro/imread#23]
Hi,

I just made a repository that will build Linux and OSX wheels for imread, here:

https://github.com/MacPython/imread-wheels

travis-ci builds the wheels:

https://travis-ci.org/MacPython/imread-wheels

and uploads them to:

https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com

I've given @luispedro admin permission to the wheel building repo.  The README at the top level of the repository should be self-explanatory.

Would you consider uploading the built wheels to pypi?   I'm happy to do that if you like, I do that for quite a few other projects (numpy, scipy, matplotlib and so on).

Thanks for imread.

**Comment by luispedro** [comment]
This is great, thank you!

Is there anything that needs to be done from my side to allow you to upload wheels to pypi?

**Comment by matthew-brett** [comment]
You're welcome.

You need to give me permission via the pypi interface - my pypi username is "matthew.brett".

**Comment by luispedro** [comment]
Done.

**Comment by matthew-brett** [comment]
Thanks - I uploaded them.   Let me know if you need help building / uploading for the next release?

**Comment by luispedro** [comment]
Sure. In the meanwhile, I'll close this issue here.
