### ISSUE TITLE
imsave does not work with 16-bit PNGs

### ISSUE THREAD

**Issue by toaarnio** [luispedro/imread#24]
First of all I want to thank you for developing the library, and especially the 16-bit PNG support. I think I've found a bug in it, though: It seems that saving 16-bit RGB data does not work properly. Only the first 5 columns in the generated file have the expected values, others contain some garbage. Note that 8-bit read/write and 16-bit read are working fine.

I'm running imread version 0.6 on 64-bit Ubuntu 14.04, tested on both Python 2.7.6 and 3.4.3.

**Comment by luispedro** [comment]
Thank you. I have been traveling, but I will try to have a look when I have more time.

**Comment by toaarnio** [comment]
I could take a shot at fixing this myself. Can you give any hints or pointers for where to start?

**Comment by luispedro** [comment]
Thank you very much for any help.

The relevant function is https://github.com/luispedro/imread/blob/8c883f270accd8c2f1d019d64bc647ed92725dd0/imread/lib/_png.cpp#L151 `void PNGFormat::write(Image* input, byte_sink* output, const options_map& opts)`

**Comment by toaarnio** [comment]
Thanks! I submitted a fix, can you make a new release and push it to PIP?

**Comment by luispedro** [comment]
I will do so! thanks.

**Comment by luispedro** [comment]
Done: https://pypi.python.org/pypi/imread/0.6.1
