### ISSUE TITLE
Compilation on Mojave / Xcode 10

### ISSUE THREAD

**Issue by wtollett-usgs** [luispedro/imread#31]
When attempting to install imread on a fresh Mojave install (Xcode 10.1), I see the following:

warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
imread/_imread.cpp:17:10: fatal error: 'sstream' file not found

This seems to be related to Apple deprecating stdlibc++ support as of 10.9/whichever xcode version that was, but officially ending the support with the latest release. I just submitted a pull request (#30), which allows compilation to go forward.

**Comment by luispedro** [comment]
Thanks for the patch, I accepted and am closing here (unfortunately, I cannot directly test it myself, but the code looked reasonable and I trust it fixes the issue on your side).
