### ISSUE TITLE
wheels?

### ISSUE THREAD

**Issue by hmaarrfk** [luispedro/imread#35]
I noticed that https://github.com/luispedro/imread/issues/23 discussed uploading wheels.

Has that effort been stalled?I ask because imread is being used by scikit-image to test the `imread` backend. Installing imread from source sometimes breaks the build system.

We also had to create a special case for it since it did not have "wheels" so we couldn't recommend our users install it by default as a general "optional dependency".

Here is an example of a troublesome build
https://travis-ci.org/scikit-image/scikit-image/jobs/530681267

**Comment by luispedro** [comment]
I uploaded wheels (for Linux), let me know if it fixes it...

**Comment by hmaarrfk** [comment]
I think the issues we are facing are building the library for OSX. Would it be possible to upload wheels for those too?

We could use the `--prefer-binary` flag, but I would prefer we stay up to date with your changes in case you make any deprecations/API changes.

**Comment by hmaarrfk** [comment]
I think this plugin is more for users that use imread, if you think few are using OSX, and that is appropriate for us to skip those tests, we could do so for OSX, though I would think of this as a suboptimal solution.

**Comment by luispedro** [comment]
I don't really have the ability to do macos versions.

**Comment by hmaarrfk** [comment]
Hmm ok. I understand. This wheel stuff is rather complicated to get right. 

Also, I think you might need to build your wheels with an older version of Linux. 

Matthew Brett's multibuikd repo helps with that, but it does have a learning curve.

The wheel you uploaded is not compatible with as old of a Linux distro as is typically targeted with standard wheels. I would maybe take down the wheels you have now.

**Comment by hmaarrfk** [comment]
I wasn't so much insisting on having wheels, more just asking if you had them hidden somewhere ;)

**Comment by luispedro** [comment]
OK, got it. I used https://github.com/pypa/python-manylinux-demo, which I expected to give me a sufficiently old version of Linux.

**Comment by hmaarrfk** [comment]
I can double check to see what went wrong with our builds. Maybe we need a system dependency?

**Comment by luispedro** [comment]
Wheels now exist for `0.7.4`
