### ISSUE TITLE
Build fails with imread 0.7.2

### ISSUE THREAD

**Issue by sciunto** [luispedro/imread#36]
In scikit-image, we have failures with the latest version of imread. I haven't seen the issue here, so I report it.

https://travis-ci.org/github/scikit-image/scikit-image/jobs/667169692?utm_medium=notification&utm_source=github_status

**Comment by luispedro** [comment]
Was scikit-learn dependent on the pre-built wheels in the past (I think this may have been the case)? I can upload new ones

**Comment by sciunto** [comment]
Yes. This is indeed scikit-image,  (see https://github.com/luispedro/imread/issues/35 )

**Comment by luispedro** [comment]
Wheels now exist for `0.7.4`. I hope this fixes your issue.
