### ISSUE TITLE
Security Address

### ISSUE THREAD

**Issue by SCH227** [luispedro/imread#42]
Hello!

I may have found a security issue in latest version of Imread. Following responsible disclosure, is there an email or other private channel where I could share the details?
Thank you

**Comment by luispedro** [comment]
You can email me at luis@luispedro.org

**Comment by SCH227** [comment]
Emailed.
I recommend [adding a SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file in your repo so reporters have clear instructions on how to handle disclosures.
Thank you for your awesome project!
